CREATE DATABASE MedicDB;
USE MedicDB;

CREATE TABLE Medic
(
	id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(20) NOT NULL,
	Pas VARCHAR(16)	NOT NULL,
	name VARCHAR(20) NOT NULL,
	surname VARCHAR(30) NOT NULL,
	adress VARCHAR(100) NOT NULL,
	med VARCHAR(100) NOT NULL,
	email VARCHAR(50) NOT NULL,
	Spec VARCHAR(100) NOT NULL,
	telephone VARCHAR(100) NOT NULL,
	idvisit INT(10) UNSIGNED
);

CREATE TABLE Patient
(
	id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(20) NOT NULL,
	pas VARCHAR(16) NOT NULL,
	name VARCHAR(20) NOT NULL,
	surname	VARCHAR(30) NOT NULL,
	sex	CHAR(1)	NOT NULL,
	adress VARCHAR(100)	NOT NULL,
	birthdate Date NOT NULL,
	telephone VARCHAR(100) NOT NULL,
	bloodtype CHAR(2) NULL,
	idvisit INT(10) UNSIGNED
);

CREATE TABLE Radiography
(
	id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	reportdate DATE NULL,
	receptiondate DATE NOT NULL,
	radiographydate	DATE NOT NULL,
	study VARCHAR(255) NOT NULL,
	report VARCHAR(255) NULL,
	controldone	VARCHAR(255) NOT NULL,
	idvisit INT(10) UNSIGNED
);

CREATE TABLE Analysis
(
	id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	analysisdate DATE NOT NULL,
	analysistype VARCHAR(50) NOT NULL,
	report VARCHAR(255) NOT NULL,
	reportdate DATE NOT NULL,
	idvisit INT(10) UNSIGNED
);

CREATE TABLE Pharmacotherapy
(
	id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	descript VARCHAR(255) NOT NULL,
	dosage VARCHAR(255) NULL,
	startdate DATE NOT NULL,
	enddate DATE NULL,
	initialweight FLOAT NULL,
	finalweight FLOAT NULL,
	medicament VARCHAR(100),
	idvisit INT(10) UNSIGNED
);

CREATE TABLE Medicament
(
	id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL
);

CREATE TABLE  Episodes
(
	id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	descript VARCHAR(255) NOT NULL,
	startdate DATE NOT NULL,
	enddate DATE NULL,
	evolution VARCHAR(255) NULL,
	disease VARCHAR(255),
	idvisit INT(10) UNSIGNED
);

CREATE TABLE Disease
(
	id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL
);

CREATE TABLE Visit
(
	id INT(10) UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	reception Date NULL,
	visitdate DATE NOT NULL,
	report VARCHAR(255) NULL,
	medicalcentre VARCHAR(100) NOT NULL,
	idanalysis INT UNSIGNED,
	idepisode INT UNSIGNED,
	idmedic INT UNSIGNED,
	idpatient INT UNSIGNED,
	idpharmacotherapy INT UNSIGNED,
	idradiography INT UNSIGNED
);